### ISSUE TITLE
no preprocessing code in repo

### ISSUE THREAD

**Issue by jordwil** [deepcelllineage/mitolin#3]
Hoping to get started with some preprocessing steps, perhaps larger scale task scheduler work. I'll need the latest stable version of the preprocessing pipeline.

**Comment by Deena-B** [comment]
Hi Jordan, 
Thanks for submitting an issue. Please have a look at the two links below.

First, to get an idea of the folder structure for the project, have a look at the [directory structure page](https://github.com/deepcelllineage/overview/wiki/dir-struct) in our Overview Wiki.

The [bash script](https://github.com/deepcelllineage/mitolin/blob/master/src/20190502-KB-gatk3-fastq2vcf.sh) that I used to run the data for the first time is in the `mitolin/src` folder. Note that this script is a couple years old. So, I expect a lot will change, especially since it should all be upgraded to gatk4.

Feel free to respond here and/or ping me through Slack as questions arise. ([Join the Slack group](http://bit.ly/JoinSlackFastaiSFbay))

**Comment by Deena-B** [comment]
Hi Jordan, 
I added a mitolin plan tutorial to the wiki. It outlines the steps that are needed for pre-processing, with links. It's basically my summary of what I got from reading gatk's website. 

The tutorial is here: https://github.com/deepcelllineage/overview/wiki/mitolinplan-v0

I'm using the word 'tutorial' loosely ;)
